name: Release Go project

on:
    push:
        tags:
            - "*"

permissions:
    contents: write

jobs:
    build:
        name: GoReleaser build
        runs-on: ubuntu-latest

        steps:
            - name: Check out code into the Go module directory
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use GoLang
              uses: actions/setup-go@v5
              with:
                  cache: true
                  cache-dependency-path: go.sum
                  go-version-file: go.mod

            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@master
              with:
                  version: latest
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
